name: Autobuild

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: benjlevesque/short-sha@v3.0
        id: short-sha

      - name: Setup
        run: |
          sudo apt-get install mingw-w64

      - name: Rustup show
        run: rustup show
      
      - name: Build
        run: cargo build --release --verbose

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: "swMod-${{ steps.short-sha.outputs.sha }}"
          path: |
            target/release/swmod-inject.exe
            target/release/swmod.dll
