name: Autobuild

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: benjlevesque/short-sha@v3.0
        id: short-sha

      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}
      
      - name: Build
        run: cargo build --release --verbose

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: "swQolSuite-${{ steps.short-sha.outputs.sha }}"
          path: |
            target/x86_64-pc-windows-msvc/release/swqols-inject.exe
            target/x86_64-pc-windows-msvc/release/swqols.dll
